# See http://www.appveyor.com/docs/appveyor-yml for reference

#---------------------------------#
#      general configuration      #
#---------------------------------#


#---------------------------------#
#    environment configuration    #
#---------------------------------#

os: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - ps: .\build.ps1 -pack

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: artifacts/*

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:

  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: R4+VK7DPGDBh/IvVDn06bAqBr/QKFS5eB9OFQZLzKsapKq1QJ+ytmHx71v7mV9oO
    artifact: artifacts/*
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true

  # MyGet
  - provider: NuGet
    server: https://www.myget.org/F/bretcope/api/v2/package
    symbol_server: https://www.myget.org/F/bretcope/symbols/api/v2/package
    api_key:
      secure: 4OhfGM3pJQHTs5OYskc448dwXt8DqPec7vdyK+G+AS5v0m8pSxyP30UoZyTanDcz
    artifact: /artifacts/.*\.nupkg/
    skip_symbols: false
    on:
      branch: master

  # NuGet.org
  - provider: NuGet
    api_key:
      secure: NiH62CvEa6ztPGnR9glvKexCL5sJStB62JcJ/8CcVJJAj7rkCzZvfN87E5xPpNd0
    artifact: /artifacts/.*\.nupkg/
    skip_symbols: false
    on:
      appveyor_repo_tag: true

